=== cryxli/ExpCraft/ExpCraftAlchemy/src/main/resources/config/recipe.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://github.com/cryxli/ExpCraft/recipe"
	elementFormDefault="qualified" xmlns:ec="http://github.com/cryxli/ExpCraft/recipe">

    <element name="recipe" type="ec:recipeType" />
    <complexType name="recipeType">
    	<sequence minOccurs="0" maxOccurs="unbounded">
    		<choice minOccurs="1" maxOccurs="1">
    			<element ref="ec:shapeless" />
    			<element ref="ec:shaped" />
    			<element ref="ec:furnace" />
    		</choice>
    	</sequence>
    </complexType>

    <element name="shapeless" type="ec:shapelessType" />
    <complexType name="shapelessType">
    	<sequence minOccurs="1" maxOccurs="1">
    		<element name="output" type="ec:item-stack" maxOccurs="1"
    			minOccurs="1" />
    		<!-- TODO -->
    		<element name="inputs" type="ec:inputs" maxOccurs="1"
    			minOccurs="1" />
    	</sequence>
    	<attribute name="exp" type="double" default="1.0">
    		<annotation>
    			<documentation>
    				Experience gained. Can be omitted when equals to one
    				experience point.
    			</documentation>
    		</annotation>
    	</attribute>
    	<attribute name="level" type="int" default="0">
    		<annotation>
    			<documentation>Required level to create this recipe.</documentation></annotation></attribute>
    </complexType>

    <element name="shaped" type="ec:shapedType" />
    <complexType name="shapedType">
    	<sequence minOccurs="1" maxOccurs="1">
    		<element name="output" type="ec:item-stack" />
    		<!-- TODO -->
    		<element name="inputs" type="ec:inputs"></element>
    	</sequence>
    	<attribute name="width" type="int" use="required"></attribute>
    	<attribute name="height" type="int" use="required"></attribute>
    	<attribute name="exp" type="double" default="1.0">
    		<annotation>
    			<documentation>
    				Experience gained. Can be omitted when equals to one
    				experience point.
    			</documentation>
    		</annotation>
    	</attribute>
    	<attribute name="level" type="int" default="0">
    		<annotation>
    			<documentation>Required level to create this recipe.</documentation></annotation></attribute>
    </complexType>

    <complexType name="inputs">
        <annotation>
        	<documentation>An item that is part of a shaped or shapeless recipe.</documentation>
        </annotation>
        <sequence>
    		<element name="item" type="ec:item-stack" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <element name="furnace" type="ec:furnaceType" />
    <complexType name="furnaceType">
    	<sequence minOccurs="1" maxOccurs="1">
    		<element name="output" type="ec:item-stack">
    			<annotation>
    				<documentation>Resulting item</documentation>
    			</annotation>
    		</element>
    		<element name="input" type="ec:item-stack">
    			<annotation>
    				<documentation>
    					Item that can be cooked.
    				</documentation>
    			</annotation>
    		</element>
    	</sequence>
    	<attribute name="exp" type="double" use="prohibited">
    		<annotation>
    			<documentation>
    				Experience gained. Disabled at the moment.
    			</documentation>
    		</annotation>
    	</attribute>
    	<attribute name="level" type="int" default="0" use="prohibited">
    		<annotation>
    			<documentation>Required level to create this recipe. Disabled at the moment.</documentation>
    		</annotation></attribute>
    </complexType>

    <complexType name="item-stack">
    	<attribute name="item" type="string" use="required">
    		<annotation>
    			<documentation>The base item. You can use the item names as defined by bukkit's Material class or the item IDs.</documentation>
    		</annotation></attribute>
    	<attribute name="data" type="int">
    		<annotation>
    			<documentation>
    				Optional data value of the item.
    			</documentation>
    		</annotation>
    	</attribute>
        <attribute name="amount" use="optional" default="1">
    		<annotation>
    			<documentation>
    				How many items are produced/requires. An amount of
    				one does not need to be specified.
    			</documentation>
    		</annotation>
    		<simpleType>
    			<restriction base="int">
    				<minInclusive value="1"></minInclusive>
    				<maxInclusive value="64"></maxInclusive>
    			</restriction>
    		</simpleType>
    	</attribute>
    </complexType>

</schema>

=== cryxli/ExpCraft/ExpCraftAlchemy/src/main/resources/config/recipe.xml
<?xml version="1.0" encoding="UTF-8"?>
<recipe xmlns="http://github.com/cryxli/ExpCraft/recipe"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://github.com/cryxli/ExpCraft/recipe recipe.xsd">

	<shapeless>
		<!-- turn sand into cobblestone -->
		<output item="COBBLESTONE" amount="2" />
		<inputs>
			<item item="SAND" />
			<item item="SAND" />
		</inputs>
	</shapeless>
	<shapeless>
		<!-- turn cobblestone into sand -->
		<output item="SAND" amount="2" />
		<inputs>
			<item item="COBBLESTONE" />
			<item item="COBBLESTONE" />
		</inputs>
	</shapeless>
	<shapeless>
		<!-- turn cobblestone and dirt into sand -->
		<output item="SAND" amount="2" />
		<inputs>
			<item item="COBBLESTONE" />
			<item item="DIRT" />
		</inputs>
	</shapeless>
	<shapeless>
		<!-- turn sand and dirt into cobblestone -->
		<output item="COBBLESTONE" amount="2" />
		<inputs>
			<item item="SAND" />
			<item item="DIRT" />
		</inputs>
	</shapeless>
	<shapeless>
		<!-- turn sand and cobblestone into dirt -->
		<output item="DIRT" amount="2" />
		<inputs>
			<item item="SAND" />
			<item item="COBBLESTONE" />
		</inputs>
	</shapeless>

	<!-- turn two half-slabs into their respective block -->
	<shaped height="2" width="1">
		<output item="COBBLESTONE" />
		<inputs>
			<item item="STEP" data="3" />
			<item item="STEP" data="3" />
		</inputs>
	</shaped>
	<shaped height="2" width="1">
		<output item="45" />
		<inputs>
			<item item="STEP" data="4" />
			<item item="STEP" data="4" />
		</inputs>
	</shaped>
	<shaped height="2" width="1">
		<output item="98" />
		<inputs>
			<item item="STEP" data="5" />
			<item item="STEP" data="5" />
		</inputs>
	</shaped>
	<shaped height="2" width="1">
		<output item="STONE" />
		<inputs>
			<item item="STEP" data="0" />
			<item item="STEP" data="0" />
		</inputs>
	</shaped>
	<shaped height="2" width="1">
		<output item="WOOD" data="0" />
		<inputs>
			<item item="WOOD_STEP" data="0" />
			<item item="WOOD_STEP" data="0" />
		</inputs>
	</shaped>
	<shaped height="2" width="1">
		<output item="WOOD" data="1" />
		<inputs>
			<item item="WOOD_STEP" data="1" />
			<item item="WOOD_STEP" data="1" />
		</inputs>
	</shaped>
	<shaped height="2" width="1">
		<output item="WOOD" data="2" />
		<inputs>
			<item item="WOOD_STEP" data="2" />
			<item item="WOOD_STEP" data="2" />
		</inputs>
	</shaped>
	<shaped height="2" width="1">
		<output item="WOOD" data="3" />
		<inputs>
			<item item="WOOD_STEP" data="3" />
			<item item="WOOD_STEP" data="3" />
		</inputs>
	</shaped>

	<shapeless>
		<!-- turn sandstone into sand -->
		<output item="SAND" amount="4" />
		<inputs>
			<item item="SANDSTONE" />
		</inputs>
	</shapeless>

	<furnace>
		<!-- smelt buckets into iron ingots -->
		<output item="IRON_INGOT" amount="3" />
		<input item="BUCKET" />
	</furnace>

	<shaped height="3" width="3" level="5">
		<!-- alter gold and rotten flesh into blaze rod -->
		<output item="BLAZE_ROD" />
		<inputs>
			<item item="ROTTEN_FLESH" />
			<item item="ROTTEN_FLESH" />
			<item item="ROTTEN_FLESH" />
			<item item="ROTTEN_FLESH" />
			<item item="GOLD_INGOT" />
			<item item="ROTTEN_FLESH" />
			<item item="ROTTEN_FLESH" />
			<item item="ROTTEN_FLESH" />
			<item item="ROTTEN_FLESH" />
		</inputs>
	</shaped>

	<!-- craft chainmail armour from stone -->
	<shaped height="2" width="3" exp="5" level="10">
		<output item="CHAINMAIL_HELMET" />
		<inputs>
			<item item="STONE" />
			<item item="STONE" />
			<item item="STONE" />
			<item item="STONE" />
			<item item="AIR" />
			<item item="STONE" />
		</inputs>
	</shaped>
	<shaped height="3" width="3" exp="8.0" level="10">
		<output item="CHAINMAIL_CHESTPLATE" />
		<inputs>
			<item item="STONE" />
			<item item="AIR" />
			<item item="STONE" />
			<item item="STONE" />
			<item item="STONE" />
			<item item="STONE" />
			<item item="STONE" />
			<item item="STONE" />
			<item item="STONE" />
		</inputs>
	</shaped>
	<shaped height="3" width="3" exp="7.0" level="10">
		<output item="CHAINMAIL_LEGGINGS" />
		<inputs>
			<item item="STONE" />
			<item item="STONE" />
			<item item="STONE" />
			<item item="STONE" />
			<item item="AIR" />
			<item item="STONE" />
			<item item="STONE" />
			<item item="AIR" />
			<item item="STONE" />
		</inputs>
	</shaped>
	<shaped height="2" width="3" exp="4.0" level="10">
		<output item="CHAINMAIL_BOOTS" />
		<inputs>
			<item item="STONE" />
			<item item="AIR" />
			<item item="STONE" />
			<item item="STONE" />
			<item item="AIR" />
			<item item="STONE" />
		</inputs>
	</shaped>

	<shapeless>
		<!-- turn saddles into leather -->
		<output item="LEATHER" />
		<inputs>
			<item item="SADDLE" />
		</inputs>
	</shapeless>

	<!-- Nether bricks from none nether materials -->
	<shaped height="3" width="3" exp="1.0" level="10">
		<output item="NETHER_BRICK" />
		<inputs>
			<item item="ROTTEN_FLESH" />
			<item item="WOOD" />
			<item item="ROTTEN_FLESH" />
			<item item="WOOD" />
			<item item="GRAVEL" />
			<item item="WOOD" />
			<item item="GRAVEL" />
			<item item="WOOD" />
			<item item="GRAVEL" />
		</inputs>
	</shaped>
</recipe>
